CC := g++ -std=c++11 

all: distance.x inversions.x maxSquare.x leader.x maxLength.x sumOfX.x maxSegment.x

distance.x: distance.cpp
	$(CC) -o distance.x distance.cpp
distance:
	./distance.x 10

inversions.x: inversions.cpp
	$(CC) -o inversions.x inversions.cpp
inversions:
	./inversions.x 10

maxSquare.x: maxSquare.cpp
	$(CC) -o maxSquare.x maxSquare.cpp
maxSquare:
	./maxSquare.x

leader.x: leader.cpp
	$(CC) -o leader.x leader.cpp
leader:
	./leader.x 10

maxLength.x: maxLength.cpp
	$(CC) -o maxLength.x maxLength.cpp
maxLength:
	./maxLength.x 10

sumOfX.x: sumOfX.cpp
	$(CC) -o sumOfX.x sumOfX.cpp
sumOfX:
	./sumOfX.x 10

maxSegment.x: maxSegment.cpp
	$(CC) -o maxSegment.x maxSegment.cpp
maxSegment:
	./maxSegment.x 10

clean:
	rm -f *.x
